LOCAL_HOST = "https://parabot.nakolenke.org"
USER_PATH = "/api/users/"
SPOTS_PATH = "/api/spots/"
CITY_PATH = "/api/city/"
OPEN_API_HOST = "https://api.openweathermap.org"
OPEN_API_PATH = "/data/2.5/forecast"