OPEN_API_HOST = "https://api.openweathermap.org"
OPEN_API_PATH = "/data/2.5/forecast"
OPEN_API_PATH_RIGHT_NOW = "/data/2.5/weather"
CUR_API_PATH = "/exchangerates_data/convert"
CUR_API_HOST = "https://api.apilayer.com"
